sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3271149877mm
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tMufTGJrzdKePzKoq9G
    access-key-secret: hbbkwPdulLXRCONvnbVcK8Q3nAuRUc
    bucket-name: skyprogram
