sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3271149877mm

  alioss:


  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx848b73c68601222e
    secret: 2e6ee87cc5048c17e70dc5e0459652f6

